services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: python:3.10.5-slim-bullseye
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]